language: clojure
services:
  - mysql
before_install:
  - cd ../../
  - git clone git@github.com:Purple-Services/common.git
  - cd Purple-Services/common
  - lein install
  - cd ../../
  - cd Purple-Services/app-service