language: clojure
services:
  - mysql
before_install:
  - cd ../
  - git clone git@github.com:Purple-Services/common.git
  - cd common
  - lein install
  - cd ../
  - git clone git@github.com:Purple-Services/opt.git
  - cd opt
  - lein install
  - cd ../
  - cd app-service